// Default Toolbar position for Pinstripe Twin

pref("kmeleon.general.toolbars_locked", true);
pref("kmeleon.display.maximized", true);
pref("kmeleon.display.backgroundImageEnabled", true);

pref("kmeleon.toolband.&Main Bar.break", 1);
pref("kmeleon.toolband.&Main Bar.index", 8);
pref("kmeleon.toolband.&Main Bar.size", 238);
pref("kmeleon.toolband.&Main Bar.visibility", true);
pref("kmeleon.toolband.&Search Buttons.break", 0);
pref("kmeleon.toolband.&Search Buttons.index", 13);
pref("kmeleon.toolband.&Search Buttons.visibility", true);
pref("kmeleon.toolband.&Search+.break", 0);
pref("kmeleon.toolband.&Search+.index", 13);
pref("kmeleon.toolband.&Search+.size", 36);
pref("kmeleon.toolband.&Search+.visibility", true);
pref("kmeleon.toolband.AdBlock Plus KM.break", 0);
pref("kmeleon.toolband.AdBlock Plus KM.index", 3);
pref("kmeleon.toolband.AdBlock Plus KM.size", 38);
pref("kmeleon.toolband.AdBlock Plus KM.visibility", true);
pref("kmeleon.toolband.Bookmarks.break", 0);
pref("kmeleon.toolband.Bookmarks.index", 2);
pref("kmeleon.toolband.Bookmarks.size", 504);
pref("kmeleon.toolband.Bookmarks.visibility", true);
pref("kmeleon.toolband.Extensions Manager.break", 0);
pref("kmeleon.toolband.Extensions Manager.index", 6);
pref("kmeleon.toolband.Extensions Manager.size", 78);
pref("kmeleon.toolband.Extensions Manager.visibility", true);
pref("kmeleon.toolband.Go Button.break", 0);
pref("kmeleon.toolband.Go Button.index", 11);
pref("kmeleon.toolband.Go Button.size", 36);
pref("kmeleon.toolband.Go Button.visibility", true);
pref("kmeleon.toolband.HTML5.break", 0);
pref("kmeleon.toolband.HTML5.index", 7);
pref("kmeleon.toolband.HTML5.size", 36);
pref("kmeleon.toolband.HTML5.visibility", true);
pref("kmeleon.toolband.KMrestart2.break", 1);
pref("kmeleon.toolband.KMrestart2.index", 0);
pref("kmeleon.toolband.KMrestart2.size", 39);
pref("kmeleon.toolband.KMrestart2.visibility", true);
pref("kmeleon.toolband.Menu.break", 0);
pref("kmeleon.toolband.Menu.index", 1);
pref("kmeleon.toolband.Menu.size", 465);
pref("kmeleon.toolband.Menu.visibility", true);
pref("kmeleon.toolband.SearchBar Ext.break", 0);
pref("kmeleon.toolband.SearchBar Ext.index", 12);
pref("kmeleon.toolband.SearchBar Ext.size", 253);
pref("kmeleon.toolband.SearchBar Ext.visibility", true);
pref("kmeleon.toolband.Tab/&Window Buttons.break", 0);
pref("kmeleon.toolband.Tab/&Window Buttons.index", 15);
pref("kmeleon.toolband.Tab/&Window Buttons.size", 59);
pref("kmeleon.toolband.Tab/&Window Buttons.visibility", true);
pref("kmeleon.toolband.Tabs.break", 1);
pref("kmeleon.toolband.Tabs.index", 14);
pref("kmeleon.toolband.Tabs.size", 1153);
pref("kmeleon.toolband.Tabs.visibility", true);
pref("kmeleon.toolband.Throbber.break", 0);
pref("kmeleon.toolband.Throbber.index", 9);
pref("kmeleon.toolband.Throbber.size", 16);
pref("kmeleon.toolband.Throbber.visibility", false);
pref("kmeleon.toolband.URL Bar.break", 0);
pref("kmeleon.toolband.URL Bar.index", 10);
pref("kmeleon.toolband.URL Bar.size", 637);
pref("kmeleon.toolband.URL Bar.visibility", true);
pref("kmeleon.toolband.UltraSurf.break", 0);
pref("kmeleon.toolband.UltraSurf.index", 4);
pref("kmeleon.toolband.UltraSurf.size", 36);
pref("kmeleon.toolband.UltraSurf.visibility", true);
pref("kmeleon.toolband.VideoSaver.break", 0);
pref("kmeleon.toolband.VideoSaver.index", 5);
pref("kmeleon.toolband.VideoSaver.size", 36);
pref("kmeleon.toolband.VideoSaver.visibility", true);
